FROM apache/spark:latest

USER root

# Install Python and pip
RUN apt-get update && \
    apt-get install -y python3 python3-pip && \
    pip3 install pyspark kafka-python

# Switch back to spark user
USER spark

# Set Python environment for PySpark
ENV PYSPARK_PYTHON=python3
